import streamlit as st
import numpy as np
import pickle

model = pickle.load(open("insurance_model_NEW.pkl", "rb"))

st.title("💊 Medical Insurance Cost Estimator")

st.write("Enter patient details below:")

# Input fields
age = st.number_input("Age", 1, 100)
sex = st.selectbox("Sex", ["male", "female"])
bmi = st.number_input("BMI")
children = st.number_input("Children", 0, 10)
smoker = st.selectbox("Smoker", ["yes", "no"])
region = st.selectbox("Region", ["northeast", "northwest", "southeast", "southwest"])

# Encoding inputs
sex = 1 if sex == "male" else 0
smoker = 1 if smoker == "yes" else 0

# Region encoding (same as training encoding)
region_northwest = 1 if region == "northwest" else 0
region_southeast = 1 if region == "southeast" else 0
region_southwest = 1 if region == "southwest" else 0

# Prediction button
if st.button("Predict Charges"):
    features = np.array([[age, sex, bmi, children, smoker,
                          region_northwest,
                          region_southeast,
                          region_southwest]])

    prediction = model.predict(features)

    st.success(f"💰 Estimated Insurance Cost: ₹ {prediction[0]:.2f}")

st.caption(
    "This is an estimated cost generated by a machine learning model "
    "and may not represent the actual insurance charges."
)
